/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': 'var(--color-surface-dim, #dadada)',
        'surface-bright': 'var(--color-surface-bright, #f9f9f9)',
        'background': 'var(--color-bg, #f9f9f9)',
        'on-background': 'var(--color-on-bg, #1a1c1c)',
        'surface-variant': 'var(--color-surface-variant, #e2e2e2)',
        'primary': 'var(--color-primary, #000000)',
        'secondary': 'var(--color-secondary, #5d5f5f)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        'outline': 'var(--color-outline, #7e7576)',
        'outline-variant': 'var(--color-outline-variant, #c4c7c7)',
        'surface': 'var(--color-surface, #f9f9f9)',
        'on-surface': 'var(--color-on-surface, #1a1c1c)',
        'surface-container': 'var(--color-surface-container, #efeded)',
        'surface-container-low': 'var(--color-surface-container-low, #f5f3f3)',
        'surface-container-lowest': 'var(--color-surface-container-lowest, #ffffff)',
        'surface-container-high': 'var(--color-surface-container-high, #e9e8e7)',
        'surface-container-highest': 'var(--color-surface-container-highest, #e3e2e2)',
        'accent': 'var(--color-accent, #000000)',
        'on-accent': 'var(--color-on-accent, #ffffff)',
        'accent-hover': 'var(--color-accent-hover, #333333)',
        'success': 'var(--color-success, #10b981)',
        'danger': 'var(--color-danger, #f43f5e)',
        'warning': 'var(--color-warning, #FEB019)',
        'teal': '#0ea5a0',
        'cyan': '#0891b2',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '24px',
        'stack-md': '40px',
        'stack-lg': '80px',
        'stack-xl': '120px',
        'gutter': '24px',
        'unit': '8px',
        'container-max': '1280px',
        'hairline': '1px',
      },
      fontFamily: {
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', fontWeight: '400' }],
      },
    },
  },
};
